(defun avm-js-mode-hook ()
  (define-key js-mode-map (kbd "<RET>") 'newline-and-indent)
  (define-key js-mode-map (kbd "C-c o") 'ff-find-other-file)
  (define-key js-mode-map (kbd "<f7>") 'compile)
  (make-local-variable 'js-indent-level)
  (setf js-indent-level 2)
  (setf js2-strict-missing-semi-warning nil)
  (setf indent-tabs-mode nil)
  (setf show-trailing-whitespace t)
  (electric-indent-mode t)
  (delete-trailing-whitespace-mode 'clean)
  (fic-mode)
  (setf js-other-file-alist '(("\\.js$" (".html"))))
  (setf ff-other-file-alist 'js-other-file-alist)
  )

(when (locate-library "js2-mode")
  (add-hook 'js2-mode-hook #'avm-js-mode-hook)
  (let ((mode (assoc "\\.jsm?\\'" auto-mode-alist)))
    (when mode
      (setf (cdr mode) 'js2-mode)))
  (let ((mode (assoc "\\.js\\'" auto-mode-alist)))
    (when mode
      (setf (cdr mode) 'js2-mode))))

(unless (locate-library "js2-mode")
  (add-hook 'js-mode-hook #'avm-js-mode-hook))
